[package]
name = "lamlock"
version = "0.2.1"
edition = "2024"
authors = ["schrodingerzhu <yifanzhu@rochester.edu>"]
description = "MCS-style flat-combining mutex with panic-awareness"
license = "MIT OR Apache-2.0"
keywords = ["mutex", "MCS", "flat-combining", "synchronization"]
categories = ["concurrency", "data-structures", "no-std"]
repository = "https://github.com/schrodingerzhu/useless"
readme = "README.md"

[features]
nightly = []

[dependencies]
linux-raw-sys = { version = "0.12.1", default-features = false, features = [
    "general",
    "no_std",
] }
syscalls = { version = "0.8.1", default-features = false }

[[bench]]
name = "lamlock-bench"
harness = false

[dev-dependencies]
criterion = "0.8.2"
